---
title: "Data"
author: "Will Brazgel"
date: "2022-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE)
```


## Libraries
```{r}
library(plyr)
library(readr)
library(dplyr)
library(stringr)
library(survival)
library(tidyverse)
```


## Baseball Reference Data
```{r}
cumulative22 = read.csv("2022_cumulative.csv", encoding="UTF-8")
cumulative21 = read.csv("2021_cumulative.csv", encoding="UTF-8")
cumulative20 = read.csv("2020_cumulative.csv", encoding="UTF-8")
cumulative19 = read.csv("2019_cumulative.csv", encoding="UTF-8")
cumulative18 = read.csv("2018_cumulative.csv", encoding="UTF-8")
cumulative17 = read.csv("2017_cumulative.csv", encoding="UTF-8")
cumulative16 = read.csv("2016_cumulative.csv", encoding="UTF-8")
cumulative15 = read.csv("2015_cumulative.csv", encoding="UTF-8")
cumulative14 = read.csv("2014_cumulative.csv", encoding="UTF-8")
cumulative13 = read.csv("2013_cumulative.csv", encoding="UTF-8")
cumulative12 = read.csv("2012_cumulative.csv", encoding="UTF-8")
cumulative11 = read.csv("2011_cumulative.csv", encoding="UTF-8")
cumulative10 = read.csv("2010_cumulative.csv", encoding="UTF-8")
cumulative09 = read.csv("2009_cumulative.csv", encoding="UTF-8")
cumulative08 = read.csv("2008_cumulative.csv", encoding="UTF-8")
cumulative07 = read.csv("2007_cumulative.csv", encoding="UTF-8")
cumulative06 = read.csv("2006_cumulative.csv", encoding="UTF-8")
cumulative05 = read.csv("2005_cumulative.csv", encoding="UTF-8")
cumulative04 = read.csv("2004_cumulative.csv", encoding="UTF-8")
cumulative03 = read.csv("2003_cumulative.csv", encoding="UTF-8")
cumulative02 = read.csv("2002_cumulative.csv", encoding="UTF-8")
cumulative01 = read.csv("2001_cumulative.csv", encoding="UTF-8")
cumulative00 = read.csv("2000_cumulative.csv", encoding="UTF-8")
```

```{r}
cumulative22$Status <- 0
cumulative21$Status <- 1
cumulative20$Status <- 1
cumulative19$Status <- 1
cumulative18$Status <- 1
cumulative17$Status <- 1
cumulative16$Status <- 1
cumulative15$Status <- 1
cumulative14$Status <- 1
cumulative13$Status <- 1
cumulative12$Status <- 1
cumulative11$Status <- 1
cumulative10$Status <- 1
cumulative09$Status <- 1
cumulative08$Status <- 1
cumulative07$Status <- 1
cumulative06$Status <- 1
cumulative05$Status <- 1
cumulative04$Status <- 1
cumulative03$Status <- 1
cumulative02$Status <- 1
cumulative01$Status <- 1
cumulative00$Status <- 1
```

```{r}
joinall <- rbind(cumulative22, cumulative21, cumulative20, cumulative19, cumulative18, cumulative17, cumulative16, cumulative15, cumulative14, cumulative13, cumulative12, cumulative11, cumulative10, cumulative09, cumulative08, cumulative07, cumulative06, cumulative05, cumulative04, cumulative03, cumulative02, cumulative01, cumulative00)
```

```{r}
joinall <- joinall %>%
    distinct(Name, .keep_all = TRUE)

joinall
```


## Baseball Reference Cleaning
```{r}
joinall <- joinall %>%
  rename(ERA_plus = `ERA.`,
         K = SO,
         K9 = SO9,
         KBB_ratio = SO.W,
         WL_ratio = W.L.) %>% 
  select(-ERA..1)
```

```{r}
joinall <- joinall %>% 
  add_row(Rk = 267, Name = "Luis Garcia HOU", Age = 25, Yrs =	3,	W = 26, L =	17, WL_ratio = .605, ERA =	3.57, G =	63, GS = 57, GF = 2, CG = 0, SHO = 0, SV =	0, IP =	325.0, H = 271, R = 136, ER =	129, HR =	43, BB = 102, IBB =	1, K = 333, 	HBP = 5, BK	= 2, WP = 18,	BF = 1325,	ERA_plus = 115,	WHIP = 1.148,	H9 = 7.5,	HR9 = 1.2, BB9 = 2.8,	K9 = 9.2,	KBB_ratio = 3.26, Name.additional = "garcilu05", Status = 0)
```

```{r}
joinall$Name = str_replace_all(joinall$Name,"\xa0"," ")

joinall$Name = str_replace(joinall$Name,"\\*","")

joinall$Name = str_replace(joinall$Name,"\\#","")

joinall$Name = str_replace(joinall$Name,"N  ez","Nunez")

joinall$Name = str_replace(joinall$Name,"F lix","Felix")

joinall$Name = str_replace(joinall$Name,"B ez","Baez")

joinall$Name = str_replace(joinall$Name,"D az","Diaz")

joinall$Name = str_replace(joinall$Name,"L pez","Lopez")

joinall$Name = str_replace(joinall$Name,"P rez","Perez")

joinall$Name = str_replace(joinall$Name,"Ru z","Ruiz")

joinall$Name = str_replace(joinall$Name,"Pe a","Pena")

joinall$Name = str_replace(joinall$Name,"Rodr guez", "Rodriguez")

joinall$Name = str_replace(joinall$Name,"Mari ez", "Marinez")

joinall$Name = str_replace(joinall$Name,"Adri n Morej n", "Adrian Morejon")

joinall$Name = str_replace_all(joinall$Name,"\\.", " ")

joinall$Name = str_remove_all(joinall$Name," ")
```

```{r}
joinall <- joinall %>% 
  filter(IP != "NA",
         IP > 10)
```

```{r}
joinall <- joinall %>% 
  mutate(SP = ifelse(GS > 5, 1,0))

joinall %>% 
  count(SP == 0)
```


## Baseball Savant Data
```{r}
savant = read.csv("savant.csv")
```


## Baseball Savant Cleaning
```{r}
savant <- savant %>% 
  select(-X.first_name,
         -last_name,
         -X,
         -player_id)
```

```{r}
savant <- savant %>%
  rename(IP = p_formatted_ip,
         BAA = batting_avg,
         OBP = on_base_percent,
         QS = p_quality_start,
         xBAA = xba,
         xOBP = xobp,
         AVG_EV = exit_velocity_avg,
         AVG_LA = launch_angle_avg,
         Barrel = barrel_batted_rate,
         Hard_Hit = hard_hit_percent,
         FPS = f_strike_percent,
         Total_Pitches = n,
         FB_Rate = n_fastball_formatted,
         FB_MPH = fastball_avg_speed,
         FB_Spin = fastball_avg_spin,
         Breaking_Rate = n_breaking_formatted,
         Breaking_MPH = breaking_avg_speed,
         Breaking_Spin = breaking_avg_spin,
         Offspeed_Rate = n_offspeed_formatted,
         Offspeed_MPH = offspeed_avg_speed,
         Offspeed_Spin = offspeed_avg_spin,
         )
```

```{r}
savant_avg <- savant %>% 
  filter(Total_Pitches != "NA") %>%
  filter(FB_Rate != "NA") %>%
  filter(Breaking_Rate != "NA") %>%
  filter(Offspeed_Rate != "NA") %>%
  group_by(Name) %>% 
  summarise(FB_Rate = mean(FB_Rate),
            FB_MPH = mean(FB_MPH),
            FB_Spin = mean(FB_Spin),
            Breaking_Rate = mean(Breaking_Rate),
            Breaking_MPH = mean(Breaking_MPH),
            Breaking_Spin = mean(Breaking_Spin),
            Offspeed_Rate = mean(Offspeed_Rate),
            Offspeed_MPH = mean(Offspeed_MPH),
            Offspeed_Spin = mean(Offspeed_Spin),
            BAA = mean(BAA),
            OBP = mean(OBP),
            xBAA = mean(xBAA),
            xOBP = mean(xOBP),
            AVG_EV = mean(AVG_EV),
            AVG_LA = mean(AVG_LA),
            Barrel = mean(Barrel),
            Hard_Hit = mean(Hard_Hit),
            FPS = mean(FPS)
            )
```

```{r}
savant_avg$Name = str_replace(savant_avg$Name,"Luis Garcia", "Luis Garcia HOU")

savant_avg$Name = str_replace_all(savant_avg$Name,"\\.", " ")

savant_avg$Name = str_remove_all(savant_avg$Name," ")
```


## Draft Data
```{r}
Draft = read.csv("Draft.csv",encoding="UTF-8")
```


## Draft Cleaning
```{r}
Draft <- Draft %>% 
  mutate(Name = name_first_last,
         Handedness = throws,
         Overall_Pick = overall,
         Round = round_desc) %>% 
  select(Name,Overall_Pick,Handedness,Round)

Draft$Name = str_replace_all(Draft$Name,"\\.", " ")

Draft$Name = str_remove_all(Draft$Name," ")
```


## Dataset Joining
```{r}
fullset <- left_join(joinall, 
                    savant_avg,
                    by = "Name")

fullset
```

```{r}
fullset_draft <- inner_join(fullset, 
                    Draft,
                    by = "Name")

fullset_draft <- fullset_draft %>% distinct(Name, .keep_all = TRUE)
```

```{r}
statcast <- inner_join(joinall,
                       savant_avg,
                       by = "Name")
statcast
```


## Variable Addition
```{r}
statcast <- statcast %>% 
  mutate(FB_Primary = ifelse(FB_Rate > 57.7, 1, 0))

statcast %>% 
  count(FB_Primary)

statcast <- statcast %>% 
  mutate(Drop_MPH = FB_MPH - Offspeed_MPH)

statcast <- statcast %>% 
  mutate(IP_perYear = IP/Yrs)
```


## Initial Exploration

### Kaplan Meier Curves
```{r}
fullset_km_IP = survfit(Surv(IP,Status)~SP, conf.type = "plain", data = fullset)

plot(fullset_km_IP, lty = 1:2)

summary(fullset_km_IP)
```

```{r}
fullset_km_yrs = survfit(Surv(Yrs,Status)~SP, conf.type = "plain", data = fullset)

plot(fullset_km_yrs, lty = 1:2)

summary(fullset_km_yrs)
```

```{r}
statcast_km_IP = survfit(Surv(IP,Status)~SP, conf.type = "plain", data = statcast)

plot(statcast_km_IP, lty = 1:2)

summary(statcast_km_IP)
```

```{r}
statcast_km_yrs = survfit(Surv(Yrs,Status)~SP, conf.type = "plain", data = statcast)

plot(statcast_km_yrs, lty = 1:2)

summary(statcast_km_yrs)
```

```{r}
km_FB_primary_yrs = survfit(Surv(Yrs,Status)~FB_Primary + strata(SP), conf.type = "plain", data = statcast)

plot(km_FB_primary_yrs, lty = 1:2)

summary(km_FB_primary_yrs)
```

```{r}
km_FB_primary_IP = survfit(Surv(IP,Status)~FB_Primary + strata(SP), conf.type = "plain", data = statcast)

plot(km_FB_primary_IP, lty = 1:2)

summary(km_FB_primary_IP)
```


### Log Rank Test
```{r}
survdiff(Surv(IP,Status)~SP, data = fullset)
```

```{r}
survdiff(Surv(Yrs,Status)~SP, data = fullset)
```

```{r}
survdiff(Surv(IP,Status)~SP, data = statcast)
```

```{r}
survdiff(Surv(Yrs,Status)~SP, data = statcast)
```

```{r}
survdiff(Surv(Yrs,Status)~FB_Primary + strata(SP), data = statcast)
```

```{r}
survdiff(Surv(IP,Status)~FB_Primary + strata(SP), data = statcast)
```

## Cox-Snell Residuals

```{r}
CoxSnell = function(cs,status,xlim=NULL,ylim=NULL)
{
kmcs = survfit( Surv(jitter(cs,amount=(max(cs)-min(cs))/1000),status) ~ 1 )$surv

plot( log(-log(kmcs)) ~ sort(log(cs)) ,
      xlab="log(Cox-Snell)", ylab="log(-log(S(Cox-Snell)))", xlim=xlim, ylim=ylim )

abline(0,1,col='red')
}
```

```{r}
survreg(Surv(IP,Status)~1, dist = "gaussian", data = statcast)
```

```{r}
CS = -log( 1 - pnorm( statcast$IP , mean = 666.4587, sd = 637.4551) )

CoxSnell( CS , statcast$Status )
```

```{r}
survreg(Surv(IP,Status)~1, dist = "exponential", data = statcast)
```

```{r}
CS = -log( 1 - pexp( statcast$IP , rate = 1/exp(6.486571)) )

CoxSnell( CS , statcast$Status )
```

```{r}
survreg(Surv(IP,Status)~1, dist = "weibull", data = statcast)
```

```{r}
CS = -log( 1 - pweibull( statcast$IP , shape = 1/(1.307044), scale = exp(6.499194) ))

CoxSnell( CS , statcast$Status )
```

```{r}
survreg(Surv(IP,Status)~1, dist = "lognormal", data = statcast)
```

```{r}
CS = -log( 1 - plnorm( statcast$IP , meanlog = 5.845299, sdlog = 1.674855))

CoxSnell( CS , statcast$Status )
```






```{r}
AIC_w = 2*(3-(-5975.5))
AIC_w
```

```{r}
AIC_lnorm = 2*(3-(-5944.6))
AIC_lnorm
```
```{r}
statcast %>% 
  count(SP == 1)
```

```{r}
statcast <- statcast %>%
  mutate(FB_Pitcher  = ifelse(FB_Rate > 55,1,0))
```


```{r}
statcast_SP <- statcast %>% 
  filter(SP == 1)
```


```{r}
statcast_RP <- statcast %>% 
  filter(SP == 0)
```

```{r}
survreg(Surv(IP,Status)~1, dist = "weibull", data = statcast_SP)
```

```{r}
CS = -log( 1 - pweibull( statcast_SP$IP , shape = 1/( 0.9718077), scale = exp(7.063609 ) ))

CoxSnell( CS , statcast_SP$Status )
```


```{r}
survreg(Surv(IP,Status)~1, dist = "lognormal", data = statcast_SP)
```

```{r}
CS = -log( 1 - plnorm( statcast_SP$IP , meanlog = 6.592084, sdlog = 1.339075))

CoxSnell( CS , statcast_SP$Status )
```

```{r}
AIC_w = 2*(3-(-2929.1))
AIC_w
```

```{r}
AIC_lnorm = 2*(3-(-2932))
AIC_lnorm
```


```{r}
survreg(Surv(IP,Status)~1, dist = "weibull", data = statcast_SP)
```

```{r}
m2 = survreg(Surv(IP,Status)~FB_Rate + FB_MPH + FB_Spin, dist = "weibull", data = statcast_SP)
summary(m2)
```

```{r}
m2_logn = survreg(Surv(IP,Status)~FB_Rate + FB_MPH + FB_Spin, dist = "lognormal", data = statcast_SP)
summary(m2_logn)
```

```{r}
m3 = survreg(Surv(IP,Status)~Breaking_Rate + Breaking_MPH + Breaking_Spin, dist = "weibull", data = statcast_SP)
summary(m3)
```

```{r}
m3_logn = survreg(Surv(IP,Status)~Breaking_Rate + Breaking_MPH + Breaking_Spin, dist = "lognormal", data = statcast_SP)
summary(m3_logn)
```

```{r}
m4 = survreg(Surv(IP,Status)~Offspeed_Rate + Offspeed_MPH + Offspeed_Spin, dist = "weibull", data = statcast_SP)
summary(m4)
```

```{r}
m4_logn = survreg(Surv(IP,Status)~Offspeed_Rate + Offspeed_MPH + Offspeed_Spin, dist = "lognormal", data = statcast_SP)
summary(m4_logn)
```

```{r}
statcast_SP %>% 
  select(Name, IP, FB_Spin, Drop_MPH, ERA) %>% 
  arrange(desc(Drop_MPH))
```

```{r}
m6 = survreg(Surv(IP,Status)~Drop_MPH, dist = "lognormal", data = statcast_SP)
summary(m6)
```

```{r}
m7 = survreg(Surv(IP,Status)~Drop_MPH, dist = "lognormal", data = statcast_SP)
summary(m7)
```

```{r}
statcast_SP_FB <- statcast_SP %>%
  filter(FB_Primary == 1)

m8 = survreg(Surv(IP,Status)~ FB_MPH, dist = "lognormal", data = statcast_SP_FB)
summary(m8)

```

```{r}
m9 = survreg(Surv(IP,Status)~ FB_MPH , dist = "lognormal", data = statcast_SP)
summary(m9)
```

```{r}
m10 = survreg(Surv(IP,Status)~Drop_MPH , dist = "lognormal", data = statcast_SP_FB)
summary(m10)
```


## RP
```{r}
survreg(Surv(IP,Status)~1, dist = "gaussian", data = statcast_RP)
```

```{r}
CS = -log( 1 - pnorm( statcast_RP$IP , mean = 220.3841, sd = 199.644  ))

CoxSnell( CS , statcast_RP$Status )
```

```{r}
survreg(Surv(IP,Status)~1, dist = "exponential", data = statcast_RP)
```

```{r}
CS = -log( 1 - pexp( statcast_RP$IP , rate = 1/exp(5.440351 )))

CoxSnell( CS , statcast_RP$Status )
```

```{r}
survreg(Surv(IP,Status)~1, dist = "weibull", data = statcast_RP)
```

```{r}
CS = -log( 1 - pweibull( statcast_RP$IP , shape = 1/(1.120017), scale = exp(5.441336) ))

CoxSnell( CS , statcast_RP$Status )
```


```{r}
survreg(Surv(IP,Status)~1, dist = "lognormal", data = statcast_RP)
```



```{r}
CS = -log( 1 - plnorm( statcast_RP$IP , meanlog = 4.861261, sdlog = 1.360014))

CoxSnell( CS , statcast_RP$Status )
```

```{r}
AIC_w = 2*(3-(-2847.8))
AIC_w
```

```{r}
AIC_lnorm = 2*(3-(-2819.7))
AIC_lnorm
```

```{r}
m2_rp = survreg(Surv(IP,Status)~FB_Rate + FB_MPH + FB_Spin, dist = "lognormal", data = statcast_RP)
summary(m2_rp)
```

```{r}
m3_rp = survreg(Surv(IP,Status)~Breaking_Rate + Breaking_MPH + Breaking_Spin, dist = "lognormal", data = statcast_RP)
summary(m3_rp)
```

```{r}
m4_rp = survreg(Surv(IP,Status)~Offspeed_Rate + Offspeed_MPH + Offspeed_Spin, dist = "lognormal", data = statcast_RP)
summary(m4_rp)
```


```{r}
m5_rp = survreg(Surv(IP,Status)~Drop_MPH, dist = "lognormal", data = statcast_RP)
summary(m5_rp)
```


```{r}
m6_rp = survreg(Surv(IP,Status)~ FB_MPH + Breaking_Spin + Breaking_MPH , dist = "lognormal", data = statcast_RP)
summary(m6_rp)
```

```{r}
m7_rp = survreg(Surv(IP,Status)~ FB_MPH + Breaking_Spin + Breaking_MPH + Offspeed_MPH, dist = "lognormal", data = statcast_RP)
summary(m7_rp)
```

```{r}
m1_fs = survreg(Surv(Yrs,Status)~ IP, dist = "weibull", data = fullset)
summary(m1_fs)
```



```{r}
fullset <- fullset %>%
  mutate(IPY = IP/Yrs)

m2_fs = survreg(Surv(Yrs,Status)~ IPY, dist = "weibull", data = fullset)
summary(m2_fs)

m3_fs = survreg(Surv(Yrs,Status)~ IP + IPY, dist = "weibull", data = fullset)
summary(m3_fs)
```

```{r}
m4_fs = survreg(Surv(Yrs,Status)~ IPY + SP, dist = "lognormal", data = fullset)
summary(m4_fs)
```

```{r}
m5_fs = survreg(Surv(Yrs,Status)~ SP, dist = "lognormal", data = fullset)
summary(m5_fs)
```

```{r}
m5_fs = survreg(Surv(IP,Status)~ SP, dist = "lognormal", data = fullset)
summary(m5_fs)
```

```{r}
km_draft = survfit(Surv(IP,Status)~Overall_Pick, conf.type = "plain", data = fullset_draft)

plot(km_draft, lty = 1:2)
```

```{r}
m_draft = survreg(Surv(IP,Status)~Overall_Pick, dist = "weibull", data = fullset_draft)
summary(m_draft)
```



```{r}
m_draft = survreg(Surv(IP,Status)~Overall_Pick, dist = "lognormal", data = fullset_draft)
summary(m_draft)
```

```{r}
fullset_draft <- fullset_draft %>%
  mutate(High_pick = ifelse(Overall_Pick < 61, 1, 0),
         Round1_pick = ifelse(Overall_Pick < 31, 1, 0),
         First10_pick = ifelse(Overall_Pick < 301, 1, 0))

m_draft1 = survreg(Surv(IP,Status)~High_pick, dist = "lognormal", data = fullset_draft)
summary(m_draft1)

m_draft2 = survreg(Surv(IP,Status)~Round1_pick, dist = "lognormal", data = fullset_draft)
summary(m_draft2)

m_draft3 = survreg(Surv(IP,Status)~First10_pick, dist = "lognormal", data = fullset_draft)
summary(m_draft3)
```

```{r}
m_draft11 = survreg(Surv(IP,Status)~High_pick, dist = "weibull", data = fullset_draft)
summary(m_draft11)

m_draft22 = survreg(Surv(IP,Status)~Round1_pick, dist = "weibull", data = fullset_draft)
summary(m_draft22)

m_draft33 = survreg(Surv(IP,Status)~First10_pick, dist = "weibull", data = fullset_draft)
summary(m_draft33)
```


```{r}
fulldata_hand <- fullset_draft %>%
  filter(Name != 'AaronBarrett',
         Name != 'JeanMachi',
         Name != 'TimHamulack',
         Name != 'BenDiggins')
  
m_hand = survreg(Surv(IP,Status)~Handedness , dist = "lognormal", data = fulldata_hand)
summary(m_hand)

m_hand1 = survreg(Surv(IP,Status)~Handedness * SP, dist = "lognormal", data = fulldata_hand)
summary(m_hand1)

```


```{r}
coxph(Surv(IP,Status)~Handedness * SP, data = fulldata_hand)
```



## Pitcher Type

### coxph
```{r}
coxph(Surv(IP,Status)~ FB_Primary, data = statcast_SP)

coxph(Surv(IP,Status)~ FB_Primary, data = statcast_RP)
```

### parametric
```{r}
survreg(Surv(IP,Status)~FB_Primary, dist = "weibull", data = statcast_SP)
survreg(Surv(IP,Status)~FB_Primary, dist = "weibull", data = statcast_RP)

```

```{r}
CS = -log( 1 - pweibull( statcast_SP$IP , shape = 1/(0.9730123), scale = exp(7.1599710 - 0.1657366*statcast_SP$FB_Primary) ))

CoxSnell( CS , statcast_SP$Status )
```



```{r}
survreg(Surv(IP,Status)~FB_Primary , dist = "lognormal", data = statcast_SP)
survreg(Surv(IP,Status)~FB_Primary , dist = "lognormal", data = statcast_RP)

d1 = survreg(Surv(IP,Status)~FB_Primary + FB_MPH, dist = "lognormal", data = statcast_SP)
d2 = survreg(Surv(IP,Status)~FB_Primary + FB_MPH, dist = "lognormal", data = statcast_RP)

summary(d1)
summary(d2)
```

```{r}
CS = -log( 1 - plnorm( statcast_SP$IP , meanlog = 6.688716 - 0.169153, sdlog = 1.339625) )

CoxSnell( CS , statcast_SP$Status )
```


```{r}
AIC_w = 2*(3-(-2927.8))
AIC_w
```

```{r}
AIC_lnorm = 2*(3-(-2930.9))
AIC_lnorm
```


```{r}
coxph(Surv(IP,Status)~K9*FB_Primary, data = statcast_SP)
```




```{r}
ipy_w = survreg(Surv(IP,Status)~IP_perYear, dist = "weibull", data = statcast_SP)
summary(ipy_w)
```


```{r}
ipy_logn = survreg(Surv(IP,Status)~IP_perYear, dist = "lognormal", data = statcast_SP)
summary(ipy_logn)
```

```{r}
ipy_w_rp = survreg(Surv(IP,Status)~IP_perYear, dist = "weibull", data = statcast_RP)
summary(ipy_w)
```


```{r}
ipy_logn_rp = survreg(Surv(IP,Status)~IP_perYear, dist = "lognormal", data = statcast_RP)
summary(ipy_logn)
```